import streamlit as st
from utils.calculations import *
from utils.decision_engine import *

# ---------------------------------------------------
# CONFIGURACIÓN DE LA PÁGINA
# ---------------------------------------------------

st.set_page_config(
    page_title="Decision Lab | Urban Mining Economics",
    page_icon="♻️",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# ---------------------------------------------------
# CSS
# ---------------------------------------------------

st.markdown("""
<style>

html, body, [class*="css"]{
    font-family: "Segoe UI", sans-serif;
}

.main{
    background-color:#F8F9FA;
}

.hero{
    text-align:center;
    padding-top:60px;
    padding-bottom:60px;
}

.hero h1{
    font-size:58px;
    color:#1E293B;
    margin-bottom:0;
}

.hero h2{
    color:#C46A1A;
    font-weight:500;
    margin-top:5px;
}

.hero h3{
    color:#475569;
    font-weight:300;
}

.tag{
    display:inline-block;
    padding:8px 20px;
    margin:6px;
    border-radius:30px;
    background:#ECEFF1;
    color:#374151;
    font-size:15px;
}

.quote{

    margin-top:50px;
    text-align:center;
    font-size:24px;
    color:#555;

}

.footer{

    margin-top:60px;
    text-align:center;
    color:#888;

}

</style>
""", unsafe_allow_html=True)

# ---------------------------------------------------
# PORTADA
# ---------------------------------------------------

st.markdown("""
<div class="hero">

# Decision Lab

## Case Study 01

# Urban Mining Economics

### A Data Analytics Approach to Urban Copper Recovery

<br>

<span class="tag">Research</span>

<span class="tag">Data Analytics</span>

<span class="tag">Decision Science</span>

<span class="tag">Urban Mining</span>

<span class="tag">Argentina</span>

</div>

""", unsafe_allow_html=True)

st.markdown("---")

st.markdown("""
<div class="quote">

### Observe.

### Analyze.

### Decide.

### Improve.

</div>
""", unsafe_allow_html=True)

st.markdown("---")

st.markdown("""

# Executive Summary

Urban Mining Economics is the first research case developed for **Decision Lab**.

The purpose of this study is to evaluate the economic feasibility of recovering copper from discarded household electrical equipment.

Instead of estimating only material recovery, the project focuses on supporting better business decisions through economic analysis, profitability estimation and asset comparison.

The application combines operational observations with data analytics to transform everyday information into actionable knowledge.

""")

st.info("Version 3.0 | Decision Lab Research Series")

st.markdown("---")

if st.button("🚀 Start Analysis", use_container_width=True):

    st.markdown("---")

    st.header("📊 Executive Dashboard")

    st.write(
        """
This dashboard summarizes the key economic indicators obtained from the
Urban Mining case study.

The objective is to provide an executive overview before exploring the
detailed analysis.
"""
    )

    col1, col2, col3, col4 = st.columns(4)

    metrics = get_executive_metrics()

    winner = best_asset()


    col1.metric(
        "🏆 Best Asset",
        winner["name"]
    )

    col2.metric(
        "💰 Monthly Profit",
        f"${winner["profit"]:,}"
    )

    col3.metric(
        "📈 ROI",
        f"{winner["roi"]}%"
    )
    
    col4.metric(
        "⭐ Recommendation",
        metrics["investment"]
    )

    st.markdown("---")

    st.subheader("🏆 Asset Ranking")

    ranking_data = ranking()

    for index, asset in enumerate(ranking_data, start=1):

        st.write(
            f"{index}. {asset['name']} | ROI: {asset['roi']}% | Profit: ${asset['profit']:,}"
        )

    st.subheader("Executive Summary")

    st.success(executive_summary())

    st.markdown("---")

    st.subheader("Key Findings")

    for item in key_findings():
        st.markdown(f"✅ {item}")

st.markdown("---")

st.header("🧠 Investment Recommendation")

rec = recommendation()

st.success(
    f"""
{rec['color']} **Recommended Asset:** {rec['asset']}

**Investment Rating:** {rec['stars']}

**Assessment:** {rec['level']}
"""
)

col1, col2, col3 = st.columns(3)

col1.metric(
    "Expected ROI",
    f"{rec['roi']}%"
)

col2.metric(
    "Estimated Profit",
    f"${rec['profit']:,}"
)

col3.metric(
    "Risk",
    rec["risk"]
)

st.info("""
This recommendation is automatically generated by the Decision Engine.

The engine evaluates all available assets and selects the option with the highest return on investment while considering the associated operational risk.
""")
st.markdown("---")

st.subheader("Why was this asset selected?")

st.markdown("""
The recommendation is based on four evaluation criteria:

✅ Highest Return on Investment (ROI)

✅ Highest Expected Monthly Profit

✅ Operational Feasibility

✅ Business Sustainability

The Decision Engine compares every evaluated asset and recommends the one that provides the best overall economic opportunity under current market conditions.
""")

st.markdown("---")

st.header("📄 Executive Report")

st.markdown("""
## Decision Summary

The Urban Mining Economics study evaluated several household electrical assets
to determine which offers the highest economic return for copper recovery.

Using profitability, ROI and operational feasibility as decision criteria,
the Decision Engine recommends prioritizing the asset with the strongest
business performance.

This recommendation is based on objective analytical indicators and provides
an evidence-based starting point for investment decisions.
""")

st.subheader("Executive Indicators")

c1, c2 = st.columns(2)

with c1:

    st.markdown("""
### Financial Perspective

- Highest ROI
- Highest Profit
- Fast Payback
- Strong Margin
- Positive Cash Flow
""")

with c2:

    st.markdown("""
### Operational Perspective

- Easy Material Recovery
- Stable Market Demand
- Medium Operational Risk
- High Business Potential
- Recommended Investment
""")
    
st.markdown("---")

st.subheader("Research Methodology")

st.markdown("""

This case study follows the Decision Lab analytical methodology.

**1. Observation**

Identify a real-world opportunity.

**2. Data Collection**

Estimate technical and economic variables.

**3. Business Analysis**

Compare all available alternatives.

**4. Decision Model**

Evaluate profitability and operational feasibility.

**5. Recommendation**

Generate an evidence-based investment recommendation.

""")
st.markdown("---")

st.subheader("Decision Lab Philosophy")

st.info("""

Observe.

Analyze.

Understand.

Decide.

Improve.

Every project developed inside Decision Lab follows this analytical framework.

Technology is only valuable when it helps people make better decisions.

""")
st.markdown("---")

st.success("""

## Final Recommendation

After evaluating all analyzed assets, the Decision Engine recommends
prioritizing **Air Conditioner recycling** as the most attractive investment
under the current assumptions.

This recommendation is supported by:

✔ Highest ROI

✔ Highest Expected Profit

✔ Sustainable Business Opportunity

✔ Favorable Operational Conditions

Decision Confidence: HIGH

""")
st.markdown("---")

st.caption("""
Decision Lab

Case Study 01

Urban Mining Economics

Version 3.0

© Mario Maciel
""")   


    
st.markdown("""

<div class="footer">

Decision Lab

Research-driven Decision Systems

Version 3.0

</div>

""", unsafe_allow_html=True)